#!/bin/bash
# Mockup HTML 檔案更名對應表
# 將檔名加上功能代碼前緩

cd /home/brian/project/game/md/v8/mockup

echo "=== Central Mockups ==="

# 根據功能矩陣對應更名
mv central/mockup_dashboard.html "central/[C01]儀表板.html" 2>/dev/null || echo "Skip: dashboard"
mv central/mockup_alert_notifications.html "central/[C05]系統通知.html" 2>/dev/null || echo "Skip: alert_notifications"
mv central/mockup_hardware_status.html "central/[C02]硬體網路狀態.html" 2>/dev/null || echo "Skip: hardware_status"
mv central/mockup_quick_actions.html "central/[L08]快速操作按鈕.html" 2>/dev/null || echo "Skip: quick_actions"
mv central/mockup_mvp_machine_list.html "central/[L05]機台列表檢視.html" 2>/dev/null || echo "Skip: mvp_machine_list"
mv central/mockup_mvp_machine_add.html "central/[C101]機台新增.html" 2>/dev/null || echo "Skip: mvp_machine_add"
mv central/mockup_machine_tags.html "central/[C107]機台標籤管理.html" 2>/dev/null || echo "Skip: machine_tags"
mv central/mockup_machine_remote_control.html "central/[C12]遠端指令.html" 2>/dev/null || echo "Skip: machine_remote_control"
mv central/mockup_machine_deploy.html "central/[L07]機台配置下發.html" 2>/dev/null || echo "Skip: machine_deploy"
mv central/mockup_machine_settings.html "central/[C14]機台設定.html" 2>/dev/null || echo "Skip: machine_settings"
mv central/mockup_machine_test.html "central/[C15]測試模式.html" 2>/dev/null || echo "Skip: machine_test"
mv central/mockup_machine_approval.html "central/[C108]機台註冊審核.html" 2>/dev/null || echo "Skip: machine_approval"
mv central/mockup_machine_key_generate.html "central/[C108]註冊金鑰產生.html" 2>/dev/null || echo "Skip: machine_key_generate"
mv central/mockup_mvp_game_add.html "central/[C16]遊戲新增.html" 2>/dev/null || echo "Skip: mvp_game_add"
mv central/mockup_game_detail.html "central/[L14]遊戲詳情.html" 2>/dev/null || echo "Skip: game_detail"
mv central/mockup_game_toggle.html "central/[C21]遊戲啟用停用.html" 2>/dev/null || echo "Skip: game_toggle"
mv central/mockup_game_version.html "central/[L10]遊戲版本管理.html" 2>/dev/null || echo "Skip: game_version"
mv central/mockup_game_supplier.html "central/[L29]遊戲供應商管理.html" 2>/dev/null || echo "Skip: game_supplier"
mv central/mockup_game_test.html "central/[C28]遊戲測試.html" 2>/dev/null || echo "Skip: game_test"
mv central/mockup_game_sync.html "central/[C55]遊戲同步管理.html" 2>/dev/null || echo "Skip: game_sync"
mv central/mockup_std_provider_list.html "central/[C53]遊戲商列表檢視.html" 2>/dev/null || echo "Skip: std_provider_list"
mv central/mockup_std_provider_add.html "central/[C103]遊戲商新增.html" 2>/dev/null || echo "Skip: std_provider_add"
mv central/mockup_api_status_monitor.html "central/[C54]API連線狀態監控.html" 2>/dev/null || echo "Skip: api_status_monitor"
mv central/mockup_api_log.html "central/[C56]API日誌查詢.html" 2>/dev/null || echo "Skip: api_log"
mv central/mockup_std_multiplayer.html "central/[C57]牌桌列表檢視.html" 2>/dev/null || echo "Skip: std_multiplayer"
mv central/mockup_std_multiplayer_add.html "central/[C57]牌桌新增.html" 2>/dev/null || echo "Skip: std_multiplayer_add"
mv central/mockup_multiplayer_config.html "central/[C59]牌桌配置管理.html" 2>/dev/null || echo "Skip: multiplayer_config"
mv central/mockup_multiplayer_history.html "central/[C60]牌局歷史查詢.html" 2>/dev/null || echo "Skip: multiplayer_history"
mv central/mockup_multiplayer_shoe.html "central/[C62]牌靴管理.html" 2>/dev/null || echo "Skip: multiplayer_shoe"
mv central/mockup_multiplayer_bet.html "central/[C63]投注額設定.html" 2>/dev/null || echo "Skip: multiplayer_bet"
mv central/mockup_multiplayer_alerts.html "central/[C65]異常狀態告警.html" 2>/dev/null || echo "Skip: multiplayer_alerts"
mv central/mockup_multiplayer_dealer.html "central/[C66]荷官操作紀錄.html" 2>/dev/null || echo "Skip: multiplayer_dealer"
mv central/mockup_login.html "central/[C70]登入.html" 2>/dev/null || echo "Skip: login"
mv central/mockup_password_reset.html "central/[C70]密碼重設.html" 2>/dev/null || echo "Skip: password_reset"
mv central/mockup_user_permission.html "central/[C71]角色權限設定.html" 2>/dev/null || echo "Skip: user_permission"
mv central/mockup_role_management.html "central/[C71]角色管理.html" 2>/dev/null || echo "Skip: role_management"
mv central/mockup_permission_matrix.html "central/[C71]權限矩陣.html" 2>/dev/null || echo "Skip: permission_matrix"
mv central/mockup_security_settings.html "central/[C71]安全設定.html" 2>/dev/null || echo "Skip: security_settings"
mv central/mockup_audit_log.html "central/[C72]操作日誌審計.html" 2>/dev/null || echo "Skip: audit_log"
mv central/mockup_flg_ota.html "central/[C74]OTA版本更新.html" 2>/dev/null || echo "Skip: flg_ota"
mv central/mockup_ota_task_deploy.html "central/[C74]OTA任務下發.html" 2>/dev/null || echo "Skip: ota_task_deploy"
mv central/mockup_announcement.html "central/[C76]公告管理.html" 2>/dev/null || echo "Skip: announcement"
mv central/mockup_std_game_category.html "central/[C77]遊戲分類管理.html" 2>/dev/null || echo "Skip: std_game_category"
mv central/mockup_std_category_add.html "central/[C77]遊戲分類新增.html" 2>/dev/null || echo "Skip: std_category_add"
mv central/mockup_game_category_management.html "central/[C77]遊戲分類管理.html" 2>/dev/null || echo "Skip: game_category_management"
mv central/mockup_lobby_settings.html "central/[C78]前端大廳配置.html" 2>/dev/null || echo "Skip: lobby_settings"
mv central/mockup_lobby_config.html "central/[C78]前端大廳設定.html" 2>/dev/null || echo "Skip: lobby_config"
mv central/mockup_flg_monitor.html "central/[C79]系統監控.html" 2>/dev/null || echo "Skip: flg_monitor"
mv central/mockup_system_monitor.html "central/[C79]系統監控.html" 2>/dev/null || echo "Skip: system_monitor"
mv central/mockup_recommended_games.html "central/[C80]推薦遊戲設定.html" 2>/dev/null || echo "Skip: recommended_games"
mv central/mockup_alert_threshold.html "central/[C83]告警閾值設定.html" 2>/dev/null || echo "Skip: alert_threshold"
mv central/mockup_log_query.html "central/[C86]日誌查詢.html" 2>/dev/null || echo "Skip: log_query"
mv central/mockup_std_system_settings.html "central/[C90]系統參數設定.html" 2>/dev/null || echo "Skip: std_system_settings"
mv central/mockup_manual_sync.html "central/[C93]手動同步.html" 2>/dev/null || echo "Skip: manual_sync"
mv central/mockup_sync_status.html "central/[L34]同步狀態檢視.html" 2>/dev/null || echo "Skip: sync_status"
mv central/mockup_sync_conflict.html "central/[L37]衝突處理.html" 2>/dev/null || echo "Skip: sync_conflict"
mv central/mockup_central_cash.html "central/[C11]開分洗分.html" 2>/dev/null || echo "Skip: central_cash"
mv central/mockup_transaction_stats.html "central/[C44]交易統計.html" 2>/dev/null || echo "Skip: transaction_stats"
mv central/mockup_flg_reconciliation.html "central/[C45]交易對帳.html" 2>/dev/null || echo "Skip: flg_reconciliation"
mv central/mockup_revenue_report.html "central/[C47]營收報表.html" 2>/dev/null || echo "Skip: revenue_report"
mv central/mockup_game_ranking.html "central/[C48]遊戲排行.html" 2>/dev/null || echo "Skip: game_ranking"
mv central/mockup_transaction_export.html "central/[C51]交易導出.html" 2>/dev/null || echo "Skip: transaction_export"
mv central/mockup_std_transaction_detail.html "central/[L16]交易詳情檢視.html" 2>/dev/null || echo "Skip: std_transaction_detail"
mv central/mockup_transaction_exception.html "central/[L19]異常交易處理.html" 2>/dev/null || echo "Skip: transaction_exception"
mv central/mockup_flg_dispute.html "central/[L20]爭議對帳處理.html" 2>/dev/null || echo "Skip: flg_dispute"
mv central/mockup_std_backup.html "central/[L28]備份與恢復.html" 2>/dev/null || echo "Skip: std_backup"
mv central/mockup_mvp_data_list.html "central/[L34]同步狀態檢視.html" 2>/dev/null || echo "Skip: mvp_data_list"
mv central/mockup_device_health.html "central/[L39]設備健康度儀表板.html" 2>/dev/null || echo "Skip: device_health"
mv central/mockup_network_monitor.html "central/[L40]網路延遲監控.html" 2>/dev/null || echo "Skip: network_monitor"
mv central/mockup_hardware_monitor.html "central/[L41]硬體軟體監控.html" 2>/dev/null || echo "Skip: hardware_monitor"
mv central/mockup_heartbeat_monitor.html "central/[L38]心跳檢測.html" 2>/dev/null || echo "Skip: heartbeat_monitor"
mv central/mockup_network_settings.html "central/[C88]網路設定.html" 2>/dev/null || echo "Skip: network_settings"
mv central/mockup_notification.html "central/[C05]系統通知.html" 2>/dev/null || echo "Skip: notification"
mv central/mockup_broadcast_management.html "central/[C81]前端版面廣播模組.html" 2>/dev/null || echo "Skip: broadcast_management"
mv central/mockup_history_export.html "central/[C67]牌局歷史匯出.html" 2>/dev/null || echo "Skip: history_export"
mv central/mockup_std_reports.html "central/[C47]營收報表.html" 2>/dev/null || echo "Skip: std_reports"
mv central/mockup_std_wallet.html "central/[C106]代理錢包管理.html" 2>/dev/null || echo "Skip: std_wallet"
mv central/mockup_commission.html "central/[C64]莊家抽水設定.html" 2>/dev/null || echo "Skip: commission"
mv central/mockup_agent_tree.html "central/[C106]代理錢包管理.html" 2>/dev/null || echo "Skip: agent_tree"
mv central/mockup_user_edit.html "central/[C70]帳號編輯.html" 2>/dev/null || echo "Skip: user_edit"

echo ""
echo "=== Local Mockups ==="

mv local/mockup_local_dashboard.html "local/[L02]機台狀態圖.html" 2>/dev/null || echo "Skip: local_dashboard"
mv local/mockup_local_cash.html "local/[C11]開分洗分.html" 2>/dev/null || echo "Skip: local_cash"
mv local/mockup_local_machine.html "local/[L06]機台狀態監控.html" 2>/dev/null || echo "Skip: local_machine"
mv local/mockup_local_sync.html "local/[L34]同步狀態檢視.html" 2>/dev/null || echo "Skip: local_sync"
mv local/mockup_local_login.html "local/[C70]本地登入.html" 2>/dev/null || echo "Skip: local_login"
mv local/mockup_local_register.html "local/[C108]機台首次設定.html" 2>/dev/null || echo "Skip: local_register"
mv local/mockup_local_system_settings.html "local/[C87]基本設定.html" 2>/dev/null || echo "Skip: local_system_settings"
mv local/mockup_mvp_local_setup.html "local/[C87]本機設定.html" 2>/dev/null || echo "Skip: mvp_local_setup"
mv local/mockup_local_game.html "local/[L11]遊戲列表檢視.html" 2>/dev/null || echo "Skip: local_game"

echo ""
echo "=== Done ==="
echo "Central mockups:"
ls -1 central/*.html 2>/dev/null | wc -l
echo "Local mockups:"
ls -1 local/*.html 2>/dev/null | wc -l